[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cb-dsa"
version = "0.1.1"
description = "A customizable CLI for automating Data Structures and Algorithms tracking."
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    { name = "Cibidharan", email = "your-email@example.com" }
]
dependencies = [
    "typer>=0.9.0",
    "rich>=13.0.0",
    "requests>=2.28.0",
    "beautifulsoup4>=4.12.0",
]

[project.scripts]
cb-dsa = "cb_dsa.main:app"
